name: Validate Terraform

on:
  workflow_call:

env:
  TERRAFORM_VERSION: "1.5.5"

defaults:
  run:
    shell: bash

jobs:
  validate-terraform:
    name: Check with a terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Format Terraform code
        run: |
          terraform fmt -recursive

      - name: Validate Terraform code
        run: |
          terraform init -backend=false -input=false -no-color
          terraform validate -no-color

      - name: Commit Terraform formatting changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'AUTOMATED ACTION: Terraform fmt completed'
          add: '*.tf'
