name: Validate Terraform

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  validate-terraform:
    name: Check with a terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
      
      - name: Do format
        run:
          terraform fmt -recursive
      - name: Check validate
        run:
          terraform init -backend=false; terraform validate
      - name: Commit terraform fmt
        uses: EndBug/add-and-commit@v9
        with:
          message: 'AUTOMATED ACTION: Terraform fmt completed'
          add: '*.tf'
